---
- name: Prepare Ubuntu machine
  hosts: symportal
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install htop
      apt:
        name: htop
        state: present

